export default {
  width: 750,
  height: 615,
  fillStyle: '#F6F5FA',
  minHeight: 1150,
  children: [
    {
      type: 'rect',
      width: 750,
      height: 300,
      fillStyle: '#696AAC',
    },
    {
      type: 'group',
      width: 650,
      x: 50,
      y: 55,
      display: 'column',
      children: [
        {
          type: 'text',
          text: '下单成功',
          font: 'bold 46px Arial',
          color: '#fff',
          textAlign: 'left',
          x: 0,
          y: 0,
        },
        {
          type: 'text',
          text: '订单编号: S20231214090709120151749',
          font: '24px Arial',
          color: '#fff',
          textAlign: 'left',
          x: 0,
          y: 25,
        },
        {
          type: 'text',
          text: '下单时间: 2023-12-14 09:07:10',
          font: '24px Arial',
          color: '#fff',
          textAlign: 'left',
          x: 0,
          y: 15,
        },
      ],
    },
    {
      type: 'group',
      width: 690,
      height: 160,
      x: 30,
      y: 232,
      fillStyle: '#fff',
      r: 20,
      children: [
        // 地址子模板
        {
          type: 'group',
          x: 0,
          y: 0,
          display: 'row',
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/statics/font/ordercenter/icon/map-label.png',
              width: 30,
              height: 36,
              x: 37,
              y: 62,
            },
            {
              type: 'group',
              x: 30,
              y: 45,
              display: 'column',
              children: [
                {
                  type: 'text',
                  text: 'sa** 186****4914 sa** 186****4914 sa** 186****4914',
                  font: '30px Arial',
                  color: '#212121',
                  textAlign: 'left',
                  maxLine: 1,
                  maxWidth: 520,
                  x: 0,
                  y: 0,
                },
                {
                  type: 'text',
                  text: '湖南省长沙市*** 湖南省长沙市*** 湖南省长沙市*** 湖南省长沙市***',
                  font: '24px Arial',
                  color: '#8E8E8E',
                  textAlign: 'left',
                  maxLine: 1,
                  maxWidth: 520,
                  x: 0,
                  y: 15,
                },
              ],
            },
          ],
        },
        // {
        //   type: 'group',
        //   x: 0,
        //   y: 0,
        //   display: 'row',
        //   children: [
        //     {
        //       type: 'image',
        //       url: 'https://image.jbzyun.cn/statics/font/ordercenter/icon/map-label.png',
        //       width: 30,
        //       height: 36,
        //       x: 37,
        //       y: 62,
        //     },
        //     {
        //       type: 'group',
        //       x: 30,
        //       y: 65,
        //       display: 'column',
        //       children: [
        //         {
        //           type: 'text',
        //           text: 'sa** 186****4914 sa** 186****4914 sa** 186****4914',
        //           font: '30px Arial',
        //           color: '#212121',
        //           textAlign: 'left',
        //           maxLine: 1,
        //           maxWidth: 520,
        //           x: 0,
        //           y: 0,
        //         },
        //       ],
        //     },
        //   ]
        // }
      ],
    },
    {
      type: 'rect',
      width: 690,
      height: 100,
      fillStyle: '#fff',
      x: 30,
      y: 420,
      r: 20,
    },
    {
      type: 'container',
      fillStyle: '#fff',
      x: 30,
      y: 420,
      r: 20,
      rb: false,
      lb: false,
      paddingTop: 0,
      paddingBottom: 30,
      paddingRight: 30,
      paddingLeft: 30,
      children: [
        {
          type: 'group',
          x: 0,
          y: 30,
          height: 145,
          display: 'row',
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/9538/2024/material/image/8ac3c92f244148cea431271f42f1de11.jpeg',
              width: 145,
              height: 145,
              x: 0,
              y: 0,
              r: 16,
            },
            {
              type: 'group',
              x: 30,
              y: 5,
              display: 'column',
              children: [
                {
                  type: 'text',
                  text: 'EVERYTHINK降噪枕护颈u型枕INK降噪枕护',
                  font: '30px Arial',
                  color: '#212121',
                  textAlign: 'left',
                  maxLine: 1,
                  maxWidth: 420,
                  x: 0,
                  y: 0,
                },
                {
                  type: 'group',
                  x: 0,
                  y: 15,
                  display: 'row',
                  children: [
                    {
                      type: 'text',
                      text: '抹茶提提提提提抹茶提提提抹抹茶提茶提提提',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      x: 0,
                      y: 0,
                      lineHeight: 30,
                      maxLine: 2,
                      maxWidth: 350,
                    },
                    {
                      type: 'text',
                      text: '✕2',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      x: 30,
                      y: 0,
                    },
                  ],
                },
                {
                  type: 'group',
                  x: 0,
                  y: 15,
                  display: 'row',
                  children: [
                    {
                      type: 'text',
                      text: '¥155.00',
                      font: '24px Arial',
                      color: '#212121',
                      textAlign: 'left',
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'text',
                      text: '原价¥199.0',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      x: 10,
                      y: 0,
                    },
                  ],
                },
              ],
            },
          ],
        },

        // 商品2
        {
          type: 'group',
          x: 0,
          y: 30,
          height: 145,
          display: 'row',
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/9538/2024/material/image/8ac3c92f244148cea431271f42f1de11.jpeg',
              // url: 'https://image.jbzyun.cn/9538/2024/material/image/a3aab10166a042b5944792584dc53eba.jpg',
              width: 145,
              height: 145,
              x: 0,
              y: 0,
              r: 16,
            },
            {
              type: 'group',
              x: 30,
              y: 5,
              display: 'column',
              children: [
                {
                  type: 'text',
                  text: 'EVERYTHINK降噪枕护颈u型枕',
                  font: '30px Arial',
                  color: '#212121',
                  textAlign: 'left',
                  maxLine: 1,
                  maxWidth: 420,
                  x: 0,
                  y: 0,
                },
                {
                  type: 'group',
                  x: 0,
                  y: 15,
                  display: 'justify',
                  children: [
                    {
                      type: 'text',
                      text: '噪枕护颈u型枕',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      auto: true,
                      x: 0,
                      y: 0,
                      lineHeight: 30,
                      maxLine: 2,
                      maxWidth: 350,
                    },
                    {
                      type: 'text',
                      text: '✕2',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      x: 30,
                      y: 0,
                    },
                  ],
                },
                {
                  type: 'group',
                  x: 0,
                  y: 15,
                  display: 'row',
                  children: [
                    {
                      type: 'text',
                      text: '¥155.00',
                      font: '24px Arial',
                      color: '#212121',
                      textAlign: 'left',
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'text',
                      text: '原价¥199.0',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      auto: true,
                      textAlign: 'left',
                      x: 10,
                      y: 0,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },

    {
      type: 'group',
      x: 0,
      y: 415,
      display: 'column',
      width: 690,
      children: [
        {
          type: 'group',
          width: 690,
          height: 80,
          fillStyle: '#fff',
          auto: true,
          x: 30,
          y: 0,
          children: [
            {
              type: 'text',
              text: '岚斐梦想家高速吹风机（多颜色可⋯等共6件商品',
              maxWidth: 640,
              width: 600,
              maxLine: 1,
              font: '26px Arial',
              color: '#555',
              textAlign: 'left',
              x: 30,
              y: 25,
            },
          ],
        },

        {
          type: 'group',
          width: 690,
          height: 10,
          fillStyle: '#fff',
          x: 30,
          y: 0,
          children: [
            {
              type: 'rect',
              width: 630,
              height: 2,
              fillStyle: '#f5f5f5',
              x: 30,
              y: 4,
            },
          ],
        },

        {
          type: 'container',
          fillStyle: '#fff',
          width: 690,
          height: 320,
          x: 30,
          y: 0,
          r: 20,
          rt: false,
          lt: false,
          paddingTop: 0,
          paddingBottom: 30,
          paddingRight: 30,
          paddingLeft: 30,
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/statics/font/ordercenter/icon/pig-label.png',
              width: 150,
              height: 150,
              x: 440,
              y: 40,
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 35,
              children: [
                {
                  type: 'text',
                  text: '商品件数',
                  font: '24px Arial',
                  color: '#8E8E8E',
                  textAlign: 'left',
                  maxLine: 1,
                  maxWidth: 420,
                  x: 0,
                  y: 0,
                },
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  width: 630,
                  display: 'row',
                  align: 'right',
                  children: [
                    {
                      type: 'text',
                      text: '4件',
                      font: '24px Arial',
                      color: '#212121',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                  ],
                },
              ],
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 35,
              children: [
                {
                  type: 'text',
                  text: '运费',
                  font: '24px Arial',
                  color: '#8E8E8E',
                  textAlign: 'left',
                  maxLine: 1,
                  maxWidth: 420,
                  x: 0,
                  y: 0,
                },
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  width: 630,
                  display: 'row',
                  align: 'right',
                  children: [
                    {
                      type: 'text',
                      text: '￥2.00',
                      font: '24px Arial',
                      color: '#212121',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                  ],
                },
              ],
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 35,
              children: [
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  children: [
                    {
                      type: 'text',
                      text: '原价总额',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'group',
                      x: 0,
                      y: 0,
                      width: 630,
                      display: 'row',
                      align: 'right',
                      children: [
                        {
                          type: 'text',
                          text: '￥1821.00',
                          font: 'bold 24px Arial',
                          color: '#212121',
                          textAlign: 'left',
                          maxLine: 1,
                          maxWidth: 420,
                          x: 0,
                          y: 0,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 35,
              children: [
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  children: [
                    {
                      type: 'text',
                      text: '商品总额',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'group',
                      x: 0,
                      y: 0,
                      width: 630,
                      display: 'row',
                      align: 'right',
                      children: [
                        {
                          type: 'text',
                          text: '￥1821.00',
                          font: 'bold 24px Arial',
                          color: '#212121',
                          textAlign: 'left',
                          maxLine: 1,
                          maxWidth: 420,
                          x: 0,
                          y: 0,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },

        {
          type: 'group',
          width: 750,
          x: 0,
          y: 50,
          display: 'row',
          align: 'center',
          vertical: 'middle',
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/9538/2024/material/image/4938d86de6094f3aba6d12d59a047a07.jpg',
              width: 40,
              height: 40,
              isCircular: true,
            },
            {
              type: 'text',
              text: '尚小店',
              font: '26px Arial',
              color: '#212121',
              x: 10,
            },
          ],
        },
      ],
    },
  ],
}
