export default {
  width: 750,
  height: 1085,
  fillStyle: '#696AAC',
  fonts: [
    {
      family: 'JDZhengHT',
      source:
        'https://image.jbzyun.cn/statics/font/jbz-iconfont/JDZhengHT-regular.ttf',
    },
  ],
  children: [
    {
      type: 'group',
      width: 690,
      x: 30,
      y: 30,
      fillStyle: '#fff',
      r: 20,
      display: 'column',
      children: [
        {
          type: 'image',
          url: 'https://image.jbzyun.cn/9538/2024/material/image/8ac3c92f244148cea431271f42f1de11.jpeg',
          width: 690,
          height: 690,
          r: 20,
          rb: false,
          lb: false,
          x: 0,
          y: 0,
        },

        {
          type: 'group',
          width: 600,
          x: 30,
          y: 30,
          display: 'row',
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/9538/2024/material/image/4938d86de6094f3aba6d12d59a047a07.jpg',
              width: 40,
              height: 40,
              x: 0,
              y: 0,
              isCircular: true,
            },
            {
              type: 'text',
              text: '尚小店',
              font: '26px Arial',
              color: '#212121',
              x: 10,
              y: 10,
            },
          ],
        },

        {
          type: 'text',
          text: 'EVERYTHINK降噪枕颈u噪枕型枕INKHINK降噪枕护颈u型枕INKHINK降噪枕护颈u护型枕INK降护',
          font: '30px Arial',
          color: '#212121',
          textAlign: 'left',
          maxLine: 2,
          maxWidth: 600,
          lineHeight: 42,
          height: 84,
          x: 30,
          y: 30,
        },

        {
          type: 'text',
          text: '共2件',
          font: '24px Arial',
          color: '#8E8E8E',
          textAlign: 'left',
          x: 30,
          y: 15,
        },

        {
          type: 'group',
          width: 600,
          x: 30,
          y: 30,
          display: 'row',
          children: [
            {
              type: 'text',
              text: '￥',
              font: '26px Arial',
              color: '#212121',
              textAlign: 'left',
              x: 0,
              y: 16,
            },
            {
              type: 'text',
              text: '399.00',
              font: '50px JDZhengHT',
              color: '#212121',
              textAlign: 'left',
              x: 2,
              y: 0,
            },
            {
              type: 'text',
              auto: true,
              text: '原价￥1989.0',
              font: '22px Arial',
              color: '#8E8E8E',
              textAlign: 'left',
              x: 10,
              y: 18,
            },
          ],
        },

        {
          type: 'container',
          x: 0,
          y: 20,
          paddingTop: 0,
          paddingBottom: 30,
          paddingRight: 0,
          paddingLeft: 30,
          fillStyle: '#F9FAFE',
          r: 20,
          rt: false,
          lt: false,
          children: [
            {
              type: 'image',
              url: 'https://image.jbzyun.cn/statics/font/ordercenter/icon/pig-label.png',
              width: 170,
              height: 170,
              x: 440,
              y: -110,
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 25,
              children: [
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  children: [
                    {
                      type: 'text',
                      text: '收货信息',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'group',
                      x: 0,
                      y: 0,
                      width: 630,
                      display: 'row',
                      align: 'right',
                      children: [
                        {
                          type: 'text',
                          text: 'Z** 152*****',
                          font: '24px Arial',
                          color: '#212121',
                          textAlign: 'left',
                          maxLine: 1,
                          maxWidth: 420,
                          x: 0,
                          y: 0,
                        },
                      ],
                    },
                  ],
                },

              ],
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 25,
              children: [
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  children: [
                    {
                      type: 'text',
                      text: '收货地址',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'group',
                      x: 0,
                      y: 0,
                      width: 630,
                      display: 'row',
                      align: 'right',
                      children: [
                        {
                          type: 'text',
                          text: '河北省 ******',
                          font: '24px Arial',
                          color: '#212121',
                          textAlign: 'left',
                          maxLine: 1,
                          maxWidth: 420,
                          x: 0,
                          y: 0,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 25,
              children: [
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  children: [
                    {
                      type: 'text',
                      text: '下单时间',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'group',
                      x: 0,
                      y: 0,
                      width: 630,
                      display: 'row',
                      align: 'right',
                      children: [
                        {
                          type: 'text',
                          text: '2023-12-14 09:07:10',
                          font: '24px Arial',
                          color: '#212121',
                          textAlign: 'left',
                          maxLine: 1,
                          maxWidth: 420,
                          x: 0,
                          y: 0,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: 'group',
              x: 0,
              y: 30,
              height: 25,
              children: [
                {
                  type: 'group',
                  x: 0,
                  y: 0,
                  children: [
                    {
                      type: 'text',
                      text: '订单编号',
                      font: '24px Arial',
                      color: '#8E8E8E',
                      textAlign: 'left',
                      maxLine: 1,
                      maxWidth: 420,
                      x: 0,
                      y: 0,
                    },
                    {
                      type: 'group',
                      x: 0,
                      y: 0,
                      width: 630,
                      display: 'row',
                      align: 'right',
                      children: [
                        {
                          type: 'text',
                          text: 'S20231214090709120151749',
                          font: '24px Arial',
                          color: '#212121',
                          textAlign: 'left',
                          maxLine: 1,
                          maxWidth: 420,
                          x: 0,
                          y: 0,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
